### ISSUE TITLE
Make a friendlier set of opis for the web view

### ISSUE THREAD

**Issue by aawdls** [dls-controls/machine-status#14]
The existing opi's are "high visibility" for display on the overhead machine status monitors.

For the browser view, this isn't so appropriate and it would be better to have something more subdued for a nicer user experience.

Something akin to the layout here http://www.cs.diamond.ac.uk/machineStatus/index.php (must be viewed from dls network), retaining the tabs which we currently have for navigation between the different views.

**Comment by aawdls** [comment]
You may decide that these are better implemented in tsx than as an opi/bob file. That would also be fine (perhaps even better).

**Comment by rjwills28** [comment]
I think the only way to change the colour scheme and layout is in the opi files. This is because the actual parsing of the opi file (including colours) is all done in cs-web-lib. As cs-web-lib should be generic I don't think it makes sense to have it do any sort of translation of colours. So I think the best way would be to create web view specific opi files and load these in. 

Do you also want the layout and things like the text size to be changed to be more friendly? Should I essentially attempt to copy the layout in the link above?

**Comment by aawdls** [comment]
Yes, I'd make a brand new opi (or bob, or tsx) file and broadly copy the layout from the old web view.

**Comment by rjwills28** [comment]
@aawdls - just to confirm that I think this issue can be closed after successful https://github.com/dls-controls/machine-status/pull/18 ?

**Comment by aawdls** [comment]
Yep - thanks
