### ISSUE TITLE
Web view: reload image

### ISSUE THREAD

**Issue by aawdls** [dls-controls/machine-status#20]
This is relatively low priority.

In the web view. If you have the app open for a long time then the current graph gets out of date. The image file is being update on the server periodically but because the URL int eh app is fixed, it doesn't get reloaded.

We should make it reload periodically.

One way to implement this may be to have a timer which sets a property on the image widget to force it to be re-rendered. I found a few suggestions for this on StackOverflow.

This isn't really something that applies more generally, asin the future we'd hope to have a proper plot widget.

**Comment by rjwills28** [comment]
I have experimented with a few different implementations of this. As we don't think it needs to be a generic implementation, I finally opted to just add the code required to the machine-status app instead of the library (which could also do it). 
I have added a timer that updates the 'src' property of the img element forcing it to reload the image every x seconds. How often the image is updated can be set by an env property. 
I append the current time to the file_name (i.e. https:xxxxx.xxx.png#123456454), which forces the browser to actually load the image from that address instead of using the cached image (which will not show any updates).

Please take a look at my implementation and let me know whether you think this is the way to go or whether we want to put it in the library. In that case we would need to make it configurable in some way (i.e. we would not want every image to have this update feature). 
Branch: https://github.com/dls-controls/machine-status/tree/reload_images

**Comment by aawdls** [comment]
Thanks for the changes. I agree with the method for implementing the reload with the appended timestamp.

I can see that we may want to do this in more places (e.g. in custom status displays). I think it should be configurable per image widget, not to all elements of type `img` in one display. So I think we should be looking for a generic implementation.

It would also be desirable to have the implementation be compatible with Phoebus (then we can be sure that all the features we use maintain compatibility). So I'd first suggest looking at whether it can be done with a Rule on the image widget. I can see that a rule can in principle be used to change the source property, but it's not obvious to me how the timeout would be implemented.

Failing this, I'd like the function to be attached to the widget in a react-y way, e.g. with an effect hook, and enabled/configured by a property which is part of the bob file spec. E.g. using classes, assuming these work in a similar way to CSS classes.

**Comment by aawdls** [comment]
I now realise my latest comment contradicts what I said in the original issue description - sorry!

**Comment by rjwills28** [comment]
I have re-worked the solution to this issue and it's now somewhere between the two suggestions I think. 

Rules: I have used the 'rules' from Phoebus/CS-Studio and created a rule in the OPI files for the image widget so that if a PV is true then display http://xxxxxx.xxx.png#1 and if false show http://xxxxxx.xxx.png#2. The PV this is based on is the simulated 'flipflop(x)' PV which switches between true and false every X seconds (configured in the OPI file). To get this working in cs-web-proto I had to add the 'flipflop' simulator (based on those that had already been created such as sine and ramp). This works in the same way. So now the image src switches and hence reloads every X seconds.

Caching: In order to get round the browser caching the image, I still had to put something into the image widget to append the timestamp to the imageFileName. This is only done when the imageFileName contains the '#'.

These changes have been made to cs-web-lib. Please review them here: https://github.com/dls-controls/cs-web-lib/tree/reload_images_with_rules

**Comment by aawdls** [comment]
Fixed with #21
