### ISSUE TITLE
Incorrect display of message string in Chrome, Edge

### ISSUE THREAD

**Issue by aawdls** [dls-controls/machine-status#3]
![image](https://user-images.githubusercontent.com/17617270/155168363-fe78ae12-29d8-4334-9d57-3485e020560c.png)

The message strings are showing non-printable characters in Chrome and Edge (not in Firefox). We suspect that this is a problem in the conversion from char arrays. It may not properly detect the end of the string.

**Comment by rjwills28** [comment]
The issue here was that the conversion from the char array to string was performed for the full array even though the latter values were 0. Some browsers were then displaying the '0' string values and hence displaying the rectangles at the end of the message as above. 
I have updated the method in the cs-web-lib to convert a char array to a string so that it terminates on the appearance of '0'. This solves the issue.
See PR in the dls-controls/cs-web-lib repo: https://github.com/dls-controls/cs-web-lib/pull/2

**Comment by rjwills28** [comment]
PR merged.
